### ISSUE TITLE
Consider using fmt library as a placeholder until we can use C++20 mode.

### ISSUE THREAD

**Issue by staffantj** [rtosholdings/riptide_cpp#37]
The existing code makes use of printf-style formatting of error / screen message strings. These are awkward since the byte length of a long differs between posix and Windows, leading to the use of very ugly macros (or worse, plain wrong code).

C++20 solves this (and soo many other things) with the introduction of the format library as part of the Standard Library. 

It's available as https://github.com/fmtlib/fmt, and is included in eg spdlog as well. It supports gcc 4.8 upwards (C++11), but is available in a C++98 version as well.

**Comment by OrestZborowski-SIG** [comment]
We have updated to modern compilers which have C++20 format available natively.
